/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0dWgY893us2
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function CandidatsVote2() {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader className="pb-0">
        <CardTitle>Electoral Results</CardTitle>
        <CardDescription>Vote count for 19 candidates in the election.</CardDescription>
      </CardHeader>
      <CardContent className="p-0">
        <div className="grid w-full border-t border-gray-200 items-center gap-4 px-6 py-4 sm:grid-cols-2">
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-cyan-600" />
            <span>John Smith</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-lime-600" />
            <span>Sarah Johnson</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-rose-600" />
            <span>Michael Williams</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-amber-600" />
            <span>Emily Brown</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-violet-600" />
            <span>David Lee</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-cyan-600" />
            <span>Olivia Moore</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-lime-600" />
            <span>James Taylor</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-rose-600" />
            <span>Emma Clark</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-amber-600" />
            <span>Daniel Rodriguez</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-violet-600" />
            <span>Grace Hall</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-cyan-600" />
            <span>Nathan White</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-lime-600" />
            <span>Lily Scott</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-rose-600" />
            <span>Andrew King</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-amber-600" />
            <span>Chloe Baker</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-violet-600" />
            <span>Lucas Evans</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-cyan-600" />
            <span>Sophia Perez</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-lime-600" />
            <span>Jack Garcia</span>
          </div>
          <div className="flex items-center gap-4 text-sm font-medium">
            <div className="w-2 h-2 rounded-full bg-rose-600" />
            <span>Isabella Martinez</span>
          </div>
        </div>
      </CardContent>
      <CardFooter className="flex items-center">
        <div className="flex items-center justify-center w-full">
          <div className="grid w-full items-center gap-4 px-6 py-4 sm:grid-cols-2">
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>John Smith</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Sarah Johnson</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Michael Williams</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Emily Brown</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>David Lee</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Olivia Moore</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>James Taylor</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Emma Clark</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Daniel Rodriguez</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Grace Hall</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Nathan White</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Lily Scott</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Andrew King</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Chloe Baker</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Lucas Evans</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Sophia Perez</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Jack Garcia</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>Isabella Martinez</span>
            </div>
          </div>
          <div aria-hidden="true" className="h-0 border-l border-gray-200" />
          <div className="grid w-full items-center gap-4 px-6 py-4 sm:grid-cols-2">
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>1,200,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>900,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>850,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>800,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>780,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>750,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>700,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>650,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>600,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>550,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>500,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>450,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>400,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>350,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>300,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>250,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>200,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>150,000</span>
            </div>
            <div className="flex items-center gap-4 text-sm font-medium">
              <span>100,000</span>
            </div>
          </div>
        </div>
      </CardFooter>
    </Card>
  )
}
