/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5LJGoCTX9B3
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function CandidatsVote8() {
  return (
    <Card className="grid gap-2 p-4">
      <CardHeader className="flex flex-col md:flex-row items-start md:items-center gap-4">
        <div className="flex flex-col">
          <CardTitle className="text-2xl">Election Results</CardTitle>
          <CardDescription className="text-base">Votes received by each candidate</CardDescription>
        </div>
        <div className="ml-auto flex items-center gap-2 md:gap-4">
          <Button className="md:ml-auto w-10 h-10" size="icon" variant="outline">
            <DownloadIcon className="w-5 h-5" />
            <span className="sr-only">Download</span>
          </Button>
        </div>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <div className="grid gap-2">
          <div className="grid grid-cols-2 items-center gap-2">
            <div className="flex items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <h3 className="font-semibold">Alice Johnson</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">#1 Candidate</p>
              </div>
            </div>
            <div className="text-right">
              <h3 className="font-semibold">42%</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">3500</p>
            </div>
          </div>
          <div />
          <div className="grid grid-cols-2 items-center gap-2">
            <div className="flex items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <h3 className="font-semibold">Bob Smith</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">#2 Candidate</p>
              </div>
            </div>
            <div className="text-right">
              <h3 className="font-semibold">28%</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">2400</p>
            </div>
          </div>
          <div />
          <div className="grid grid-cols-2 items-center gap-2">
            <div className="flex items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <h3 className="font-semibold">Eve Williams</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">#3 Candidate</p>
              </div>
            </div>
            <div className="text-right">
              <h3 className="font-semibold">20%</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">1700</p>
            </div>
          </div>
          <div />
        </div>
        <div />
        <div className="grid gap-2 md:grid-cols-2 lg:grid-cols-4">
          <div className="flex items-center gap-2">
            <UserIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
            <div className="font-semibold">Total Votes</div>
            <div className="ml-auto font-semibold">8300</div>
          </div>
          <div className="flex items-center gap-2">
            <UsersIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
            <div className="font-semibold">Eligible Voters</div>
            <div className="ml-auto font-semibold">10000</div>
          </div>
          <div className="flex items-center gap-2">
            <TrendingUpIcon className="h-4 w-4 text-gray-500 dark:text-gray-400" />
            <div className="font-semibold">Turnout</div>
            <div className="ml-auto font-semibold">83%</div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}


function DownloadIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}


function UserIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function UsersIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function TrendingUpIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>
  )
}
