/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AjtmtPwEkWj
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function CandidatsVote10() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Election Results</CardTitle>
        <CardDescription>Vote distribution for each candidate</CardDescription>
      </CardHeader>
      <CardContent className="flex items-center justify-center p-12">
        <div className="grid w-full max-w-sm gap-2 text-center">
          <h3 className="font-bold">Results</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">Based on 100% of precincts reporting</p>
          <div className="flex items-center gap-4">
            <div className="w-2 h-2 rounded-full bg-cyan-600" />
            <div className="flex-1 grid gap-1">
              <h4 className="font-semibold">Samantha Green</h4>
              <h5 className="font-semibold text-sm">Green Party</h5>
            </div>
            <div className="text-right">
              <h4 className="font-semibold">42%</h4>
              <h5 className="text-xs text-gray-500 dark:text-gray-400">12,345,678 votes</h5>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="w-2 h-2 rounded-full bg-yellow-500" />
            <div className="flex-1 grid gap-1">
              <h4 className="font-semibold">Michael Blue</h4>
              <h5 className="font-semibold text-sm">Liberty Party</h5>
            </div>
            <div className="text-right">
              <h4 className="font-semibold">35%</h4>
              <h5 className="text-xs text-gray-500 dark:text-gray-400">10,345,678 votes</h5>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="w-2 h-2 rounded-full bg-purple-600" />
            <div className="flex-1 grid gap-1">
              <h4 className="font-semibold">Olivia Purple</h4>
              <h5 className="font-semibold text-sm">Purple Party</h5>
            </div>
            <div className="text-right">
              <h4 className="font-semibold">23%</h4>
              <h5 className="text-xs text-gray-500 dark:text-gray-400">6,345,678 votes</h5>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="w-2 h-2 rounded-full bg-red-500" />
            <div className="flex-1 grid gap-1">
              <h4 className="font-semibold">William Red</h4>
              <h5 className="font-semibold text-sm">Red Party</h5>
            </div>
            <div className="text-right">
              <h4 className="font-semibold">5%</h4>
              <h5 className="text-xs text-gray-500 dark:text-gray-400">1,345,678 votes</h5>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
