/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9SMM0jKziGs
 */
import { CardContent, CardFooter, Card } from "@/components/ui/card"

export function CandidatsVote5() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Ella Hughes</h3>
            <p className="text-sm font-medium leading-none">Purple</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,241,900</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">22.6%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Mia Johnson</h3>
            <p className="text-sm font-medium leading-none">Teal</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">2,891,210</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">20.1%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Aiden Lee</h3>
            <p className="text-sm font-medium leading-none">Orange</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,019,550</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">21.0%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Sophia King</h3>
            <p className="text-sm font-medium leading-none">Pink</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,112,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">21.7%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Noah White</h3>
            <p className="text-sm font-medium leading-none">White</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">2,981,300</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">20.7%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Ethan Green</h3>
            <p className="text-sm font-medium leading-none">Green</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,091,750</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">21.5%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Liam Brown</h3>
            <p className="text-sm font-medium leading-none">Brown</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,002,100</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">20.9%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Ava Black</h3>
            <p className="text-sm font-medium leading-none">Black</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,211,800</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">22.4%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Olivia Grey</h3>
            <p className="text-sm font-medium leading-none">Grey</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,051,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">21.2%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">James Red</h3>
            <p className="text-sm font-medium leading-none">Red</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,121,650</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">21.7%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">William Gold</h3>
            <p className="text-sm font-medium leading-none">Gold</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,001,800</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">20.9%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Chloe Silver</h3>
            <p className="text-sm font-medium leading-none">Silver</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,211,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">22.4%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Evelyn Cyan</h3>
            <p className="text-sm font-medium leading-none">Cyan</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,001,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">20.9%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Logan Lime</h3>
            <p className="text-sm font-medium leading-none">Lime</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,211,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">22.4%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Harper Maroon</h3>
            <p className="text-sm font-medium leading-none">Maroon</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,001,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">20.9%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Riley Azure</h3>
            <p className="text-sm font-medium leading-none">Azure</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,211,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">22.4%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
      <div className="flex flex-col gap-1.5">
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Finley Plum</h3>
            <p className="text-sm font-medium leading-none">Plum</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,001,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">20.9%</span>
            </div>
          </CardFooter>
        </Card>
        <Card>
          <CardContent className="flex flex-col items-center gap-2 p-4">
            <img
              alt="Candidate"
              className="rounded-full"
              height="120"
              src="/placeholder.svg"
              style={{
                aspectRatio: "120/120",
                objectFit: "cover",
              }}
              width="120"
            />
            <h3 className="text-lg font-semibold">Skyler Saffron</h3>
            <p className="text-sm font-medium leading-none">Saffron</p>
          </CardContent>
          <CardFooter className="flex justify-between p-4">
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Votes</span>
              <span className="text-sm font-semibold leading-none">3,211,400</span>
            </div>
            <div className="flex flex-col text-sm">
              <span className="font-semibold">Percentage</span>
              <span className="text-sm font-semibold leading-none">22.4%</span>
            </div>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}
