/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/W6Vp5zzI32T
 */


export function CandidatsVote7() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Smith, Emma</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-4" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-2" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-13" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Garcia, Sofia</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-7" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-3" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-9" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Rodriguez, Noah</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-5" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-4" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-10" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Hernandez, Liam</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-6" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-5" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-8" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Martinez, Oliver</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-8" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-6" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-5" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Gonzalez, Harper</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-3" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-7" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-9" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Lopez, Aria</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-11" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-1" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-7" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Perez, Mila</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-9" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-3" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-7" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Torres, Ethan</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-2" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-8" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-9" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Flores, Alexander</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-12" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-2" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-5" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Rivera, Camila</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-13" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-3" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-3" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Long, Leo</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-14" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-2" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-3" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Scott, Henry</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-15" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-1" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-3" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Adams, Chloe</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-16" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-2" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-1" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold">40%</div>
          <div className="font-semibold text-[#3b82f6]">4,512,345</div>
          <div className="font-semibold text-right">10%</div>
        </div>
      </div>
      <div className="grid grid-rows-1 gap-2">
        <div className="grid grid-cols-3 items-center gap-2">
          <div className="font-semibold">Baker, Scarlett</div>
          <div className="text-sm text-gray-500 col-span-2 text-right">
            <span>45,123,456 votes</span>
          </div>
        </div>
        <div className="h-2 rounded-lg bg-gray-100 shrink-0" />
        <div className="grid grid-cols-19 items-center gap-1">
          <div className="h-2 rounded-lg bg-[#3b82f6] col-span-17" />
          <div className="h-2 rounded-lg bg-[#f59e0b] col-span-1" />
          <div className="h-2 rounded-lg bg-[#10b981] col-span-1" />
        </div>
        <div className="grid grid-cols-3 items-center gap-2 text-sm">
          <div className="font-semibold" />
        </div>
      </div>
    </div>
  )
}
