/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bXYNpxb9Z8D
 */
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { Card } from "@/components/ui/card"
import React from 'react';

export function CardCandidat(){
  return (
    <Card className="w-[356px] bg-white p-4 rounded-lg shadow-md flex items-center">
      <div className="flex items-center space-x-4">
        <Avatar>
          <AvatarImage alt="{props.nom}" src="/img.png" />
        </Avatar>
        <div>
          <h3 className="font-semibold text-lg">Bassirou</h3>
          <p className="text-sm text-gray-600">Vote Obtenu : 567</p>
          <div className="text-2xl font-bold text-[#bd1e59]">18%</div>
        </div>
      </div>
    </Card>
  )
}
