/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Kc6sSYnMKNO
 */
import { CardTitle, CardDescription, CardHeader, Card, CardContent } from "@/components/ui/card"
import { RecentSales } from "./dashboard/components/recent-sales"

export function Candidats6(props:any) {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader className="flex flex-col gap-1">
        <CardTitle className="text-2xl">{props.nom}</CardTitle>
        <CardDescription>Essential information about the candidate's performance.</CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <div className="grid grid-cols-2 gap-4">
          <Card className="p-4">
            <CardTitle className="text-sm font-medium">Total Votes</CardTitle>
            <CardTitle className="text-3xl font-bold">4,231,231</CardTitle>
          </Card>
          <Card className="p-4">
            <CardTitle className="text-sm font-medium">Percentage of Votes</CardTitle>
            <CardTitle className="text-3xl font-bold">45.2%</CardTitle>
          </Card>
        </div>
        <Card>
              <CardHeader>
                          <CardTitle>Recent Sales</CardTitle>
                          <CardDescription>
                            You made 265 sales this month.
                          </CardDescription>
                        </CardHeader>
                        <CardContent>
                          <RecentSales />
                        </CardContent>
                      </Card>
            </CardContent>
        </Card>
   
  )
}
