/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lvoVstU4ueC
 */
import { CardContent, Card } from "@/components/ui/card"

export function CandidatsVote4() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      <Card>
        <CardContent className="flex">
          <img
            alt="Jasmine Young"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Jasmine Young</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#FFD700] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                25%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Ethan Williams"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Ethan Williams</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#FF6347] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                18%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Emma Martin"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Emma Martin</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#20B2AA] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                32%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Sophia Lee"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Sophia Lee</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#9370DB] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                27%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Aiden Johnson"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Aiden Johnson</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#87CEEB] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                14%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Noah Brown"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Noah Brown</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#32CD32] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                42%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Olivia Perez"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Olivia Perez</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#FF4500] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                20%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="William King"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">William King</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#1E90FF] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                35%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="James Garcia"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">James Garcia</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#FF69B4] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                23%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Charlotte Martinez"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Charlotte Martinez</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#FFD700] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                25%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Lucas Thomas"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Lucas Thomas</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#FF6347] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                18%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Riley Walker"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Riley Walker</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#20B2AA] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                32%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Avery Scott"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Avery Scott</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#9370DB] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                27%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Evelyn Perez"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Evelyn Perez</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#87CEEB] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                14%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Logan Wilson"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Logan Wilson</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#32CD32] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                42%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex">
          <img
            alt="Sofia Garcia"
            className="rounded-full"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64"
          />
          <div className="flex-1 grid gap-1 ml-4">
            <h2 className="text-lg font-semibold leading-none">Sofia Garcia</h2>
            <div className="flex items-center gap-4">
              <div className="w-3 h-12 rounded-lg bg-[#FF4500] border border-gray-200 border-gray-200" />
              <p className="text-sm font-medium not-italic text-gray-500">
                20%
                <span className="sr-only">Voted</span>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
