/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yFpiVgQpCB0
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Candidats8() {
  return (
    <div className="grid gap-4 md:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">
      <Card>
        <CardHeader className="flex flex-col items-center space-y-0">
          <img
            alt="Candidate"
            className="rounded-full"
            height="96"
            src="/placeholder.svg"
            style={{
              aspectRatio: "96/96",
              objectFit: "cover",
            }}
            width="96"
          />
          <CardTitle className="text-xl font-bold">Mamadou Sall</CardTitle>
          <CardDescription className="text-sm font-medium">Independent</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center space-y-2">
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Total Votes</h3>
            <p className="text-2xl font-semibold">1,234,567</p>
          </div>
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Percentage</h3>
            <p className="text-2xl font-semibold">25.4%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-col items-center space-y-0">
          <img
            alt="Candidate"
            className="rounded-full"
            height="96"
            src="/placeholder.svg"
            style={{
              aspectRatio: "96/96",
              objectFit: "cover",
            }}
            width="96"
          />
          <CardTitle className="text-xl font-bold">Aminata Diop</CardTitle>
          <CardDescription className="text-sm font-medium">Democratic Party</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center space-y-2">
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Total Votes</h3>
            <p className="text-2xl font-semibold">3,456,789</p>
          </div>
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Percentage</h3>
            <p className="text-2xl font-semibold">45.6%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-col items-center space-y-0">
          <img
            alt="Candidate"
            className="rounded-full"
            height="96"
            src="/placeholder.svg"
            style={{
              aspectRatio: "96/96",
              objectFit: "cover",
            }}
            width="96"
          />
          <CardTitle className="text-xl font-bold">Ousmane Ndiaye</CardTitle>
          <CardDescription className="text-sm font-medium">Republican Party</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center space-y-2">
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Total Votes</h3>
            <p className="text-2xl font-semibold">2,345,678</p>
          </div>
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Percentage</h3>
            <p className="text-2xl font-semibold">30.9%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-col items-center space-y-0">
          <img
            alt="Candidate"
            className="rounded-full"
            height="96"
            src="/placeholder.svg"
            style={{
              aspectRatio: "96/96",
              objectFit: "cover",
            }}
            width="96"
          />
          <CardTitle className="text-xl font-bold">Fatou Camara</CardTitle>
          <CardDescription className="text-sm font-medium">Green Party</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center space-y-2">
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Total Votes</h3>
            <p className="text-2xl font-semibold">1,234,567</p>
          </div>
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Percentage</h3>
            <p className="text-2xl font-semibold">15.2%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-col items-center space-y-0">
          <img
            alt="Candidate"
            className="rounded-full"
            height="96"
            src="/placeholder.svg"
            style={{
              aspectRatio: "96/96",
              objectFit: "cover",
            }}
            width="96"
          />
          <CardTitle className="text-xl font-bold">Moussa Ba</CardTitle>
          <CardDescription className="text-sm font-medium">Liberty Party</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center space-y-2">
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Total Votes</h3>
            <p className="text-2xl font-semibold">1,234,567</p>
          </div>
          <div className="grid gap-0.5 text-center">
            <h3 className="text-sm font-medium tracking-wider uppercase">Percentage</h3>
            <p className="text-2xl font-semibold">10.1%</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
