/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XtFsjtsJjzQ
 */
import { CardContent, Card } from "@/components/ui/card"

export function CandidatsVote6() {
  return (
    <div className="grid md:grid-cols-2 gap-4 w-full max-w-3xl">
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 1</h3>
            <p className="text-sm leading-none">Gray</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">2,345</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">23%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 2</h3>
            <p className="text-sm leading-none">Red</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">3,456</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">34%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 3</h3>
            <p className="text-sm leading-none">Blue</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">4,567</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">45%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 4</h3>
            <p className="text-sm leading-none">Green</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">5,678</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">56%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 5</h3>
            <p className="text-sm leading-none">Yellow</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">6,789</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">67%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 6</h3>
            <p className="text-sm leading-none">Purple</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">7,890</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">78%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 7</h3>
            <p className="text-sm leading-none">Cyan</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">8,901</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">89%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 8</h3>
            <p className="text-sm leading-none">Teal</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">9,012</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">90%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 9</h3>
            <p className="text-sm leading-none">Lime</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">10,123</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">100%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 10</h3>
            <p className="text-sm leading-none">Red</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">3,456</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">34%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 11</h3>
            <p className="text-sm leading-none">Blue</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">4,567</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">45%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 12</h3>
            <p className="text-sm leading-none">Green</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">5,678</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">56%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 13</h3>
            <p className="text-sm leading-none">Yellow</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">6,789</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">67%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 14</h3>
            <p className="text-sm leading-none">Purple</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">7,890</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">78%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 15</h3>
            <p className="text-sm leading-none">Cyan</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">8,901</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Percentage</p>
            <p className="text-sm font-bold">89%</p>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardContent className="flex flex-col gap-2">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Image"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
          </div>
          <div className="grid gap-0.5">
            <h3 className="text-sm font-bold tracking-wide">Candidate 16</h3>
            <p className="text-sm leading-none">Teal</p>
          </div>
        </CardContent>
        <CardContent className="flex flex-row items-center gap-4">
          <div className="grid gap-0.5 text-center">
            <p className="text-xs font-semibold tracking-wide uppercase">Votes</p>
            <p className="text-sm font-bold">9,012</p>
          </div>
          <div className="border-l border-gray-200 h-8" />
        </CardContent>
      </Card>
    </div>
  )
}
