/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3gEvBarQi8q
 */
// import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function CandidatsVote1() {
  return (
    <div className="flex flex-col w-full space-y-4">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <div className="flex items-center gap-2 text-lg font-semibold">
          <Package2Icon className="w-6 h-6" />
          <span className="sr-only">Acme Inc</span>
        </div>
        <nav className="hidden gap-5 text-sm md:flex md:items-center lg:gap-6">
          <a className="font-bold" href="#">
            Home
          </a>
          <a className="text-gray-500 dark:text-gray-400" href="#">
            Candidates
          </a>
          <a className="text-gray-500 dark:text-gray-400" href="#">
            Analytics
          </a>
        </nav>
        <div className="ml-auto flex items-center gap-4">
          <Button className="rounded-full" size="sm" variant="outline">
            Upgrade plan
          </Button>
          <Button className="rounded-full" size="icon" variant="ghost">
            <BellIcon className="h-4 w-4" />
            <span className="sr-only">Toggle notifications</span>
          </Button>
          <div>
            <div className="rounded-full overflow-hidden flex items-center gap-2">
              <img
                alt="Avatar"
                className="rounded-full"
                height="32"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "32/32",
                  objectFit: "cover",
                }}
                width="32"
              />
              <span className="text-sm font-medium">John Doe</span>
            </div>
            <div>
              <div>
                <UserIcon className="w-4 h-4 mr-2" />
                Profile
              </div>
              <div>
                <GaugeIcon className="w-4 h-4 mr-2" />
                Settings
              </div>
              <div />
              <div>
                <LogOutIcon className="w-4 h-4 mr-2" />
                Logout
              </div>
            </div>
          </div>
        </div>
      </header>
      <main className="grid min-h-[calc(100vh_-_theme(spacing.16))] grid-cols-1 gap-4 p-4 md:gap-8 md:p-10">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <div className="flex items-center space-x-2">
              <img
                alt="Avatar"
                className="rounded-full"
                height="32"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "32/32",
                  objectFit: "cover",
                }}
                width="32"
              />
              <div className="flex flex-col">
                <CardTitle className="text-base font-bold">2024 Election Results</CardTitle>
                <CardDescription className="text-sm">Results of the recent election</CardDescription>
              </div>
            </div>
            <Button size="sm">Export</Button>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                  <CardTitle className="text-sm font-medium">Total Votes</CardTitle>
                  <UsersIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">+12,234</div>
                  <p className="text-xs text-gray-500 dark:text-gray-400">+19% from last month</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                  <CardTitle className="text-sm font-medium">Registered Voters</CardTitle>
                  <UsersIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">+12,234</div>
                  <p className="text-xs text-gray-500 dark:text-gray-400">+19% from last month</p>
                </CardContent>
              </Card>
            </div>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                  <CardTitle className="text-sm font-medium">Total Candidates</CardTitle>
                  <UsersIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">19</div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                  <CardTitle className="text-sm font-medium">Voter Turnout</CardTitle>
                  <UsersIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">45%</div>
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-base font-bold">Results</CardTitle>
            <Button size="xs">Refresh</Button>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Rank</TableHead>
                  <TableHead>Image</TableHead>
                  <TableHead>Candidate</TableHead>
                  <TableHead>Votes</TableHead>
                  <TableHead>Percentage</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-semibold">1</TableCell>
                  <TableCell className="flex items-center space-x-2">
                    <img
                      alt="Avatar"
                      className="rounded-full"
                      height="24"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "24/24",
                        objectFit: "cover",
                      }}
                      width="24"
                    />
                  </TableCell>
                  <TableCell>John Doe</TableCell>
                  <TableCell>5,230</TableCell>
                  <TableCell>45%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-semibold">2</TableCell>
                  <TableCell className="flex items-center space-x-2">
                    <img
                      alt="Avatar"
                      className="rounded-full"
                      height="24"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "24/24",
                        objectFit: "cover",
                      }}
                      width="24"
                    />
                  </TableCell>
                  <TableCell>Jane Smith</TableCell>
                  <TableCell>4,230</TableCell>
                  <TableCell>35%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-semibold">3</TableCell>
                  <TableCell className="flex items-center space-x-2">
                    <img
                      alt="Avatar"
                      className="rounded-full"
                      height="24"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "24/24",
                        objectFit: "cover",
                      }}
                      width="24"
                    />
                  </TableCell>
                  <TableCell>Michael Johnson</TableCell>
                  <TableCell>2,230</TableCell>
                  <TableCell>20%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-semibold">4</TableCell>
                  <TableCell className="flex items-center space-x-2">
                    <img
                      alt="Avatar"
                      className="rounded-full"
                      height="24"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "24/24",
                        objectFit: "cover",
                      }}
                      width="24"
                    />
                  </TableCell>
                  <TableCell>Sarah Lee</TableCell>
                  <TableCell>1,230</TableCell>
                  <TableCell>10%</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function GaugeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 14 4-4" />
      <path d="M3.34 19a10 10 0 1 1 17.32 0" />
    </svg>
  )
}


function LogOutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
