/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gidKXOjYl0c
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function CandidatsVote9() {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader className="flex flex-col gap-1">
        <CardTitle>Vote Overview</CardTitle>
        <CardDescription>Results of the election for the top 3 candidates.</CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <div className="grid w-full gap-1.5 text-xs md:grid-cols-3 md:gap-1.5 md:text-sm">
          <div className="font-semibold">1. Alexander Johnson</div>
          <div className="text-gray-500 dark:text-gray-400">+1200 votes</div>
          <div className="text-right">40%</div>
          <div className="font-semibold">2. Emma Smith</div>
          <div className="text-gray-500 dark:text-gray-400">+1100 votes</div>
          <div className="text-right">37%</div>
          <div className="font-semibold">3. Michael Thompson</div>
          <div className="text-gray-500 dark:text-gray-400">+900 votes</div>
          <div className="text-right">23%</div>
        </div>
        <div className="h-0.5 bg-gray-100 rounded-full dark:bg-gray-800" />
        <div className="grid w-full gap-1.5 text-xs md:grid-cols-3 md:gap-1.5 md:text-sm">
          <div className="font-semibold">4. Sophia Lee</div>
          <div className="text-gray-500 dark:text-gray-400">+200 votes</div>
          <div className="text-right">7%</div>
          <div className="font-semibold">5. William Garcia</div>
          <div className="text-gray-500 dark:text-gray-400">+150 votes</div>
          <div className="text-right">5%</div>
        </div>
      </CardContent>
    </Card>
  )
}
