/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EbiovqwwbbV
 */
import { CardHeader, CardTitle, CardDescription, CardContent, Card } from "@/components/ui/card"
// import { ResponsiveLine } from "@nivo/line"

export function Candidats7() {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader className="flex flex-col items-center space-y-2">
        <img
          alt="Candidate"
          className="rounded-full border"
          height="96"
          src="/placeholder.svg"
          style={{
            aspectRatio: "96/96",
            objectFit: "cover",
          }}
          width="96"
        />
        <div className="flex flex-col items-center space-y-1 text-center">
          <div className="font-bold">Moussa Diop</div>
          <div className="text-sm text-gray-500 dark:text-gray-400">Presidential Candidate</div>
        </div>
      </CardHeader>
      <CardContent className="flex flex-col space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="flex flex-col gap-1">
            <div className="text-sm text-gray-500 dark:text-gray-400">Total Votes</div>
            <div className="text-2xl font-bold">4,231,901</div>
          </div>
          <div className="flex flex-col gap-1">
            <div className="text-sm text-gray-500 dark:text-gray-400">Percentage of Votes</div>
            <div className="text-2xl font-bold">42.3%</div>
          </div>
        </div>
        <Card className="w-full">
          <CardHeader className="pb-0">
            <CardTitle>Vote Breakdown</CardTitle>
            <CardDescription>Percentage of votes by region</CardDescription>
          </CardHeader>
          <CardContent className="h-[300px]">
            {/* <CurvedlineChart className="w-full aspect-[2/1]" /> */}
          </CardContent>
        </Card>
      </CardContent>
    </Card>
  )
}


// function CurvedlineChart(props: any) {
//   return (
//     <div {...props}>
//       <div
//         data={[
//           {
//             id: "Desktop",
//             data: [
//               { x: "Jan", y: 43 },
//               { x: "Feb", y: 137 },
//               { x: "Mar", y: 61 },
//               { x: "Apr", y: 145 },
//               { x: "May", y: 26 },
//               { x: "Jun", y: 154 },
//             ],
//           },
//           {
//             id: "Mobile",
//             data: [
//               { x: "Jan", y: 60 },
//               { x: "Feb", y: 48 },
//               { x: "Mar", y: 177 },
//               { x: "Apr", y: 78 },
//               { x: "May", y: 96 },
//               { x: "Jun", y: 204 },
//             ],
//           },
//         ]}
//         margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
//         xScale={{
//           type: "point",
//         }}
//         yScale={{
//           type: "linear",
//           min: 0,
//           max: "auto",
//         }}
//         curve="monotoneX"
//         axisTop={null}
//         axisRight={null}
//         axisBottom={{
//           tickSize: 0,
//           tickPadding: 16,
//         }}
//         axisLeft={{
//           tickSize: 0,
//           tickValues: 5,
//           tickPadding: 16,
//         }}
//         colors={["#2563eb", "#e11d48"]}
//         pointSize={6}
//         useMesh={true}
//         gridYValues={6}
//         theme={{
//           tooltip: {
//             chip: {
//               borderRadius: "9999px",
//             },
//             container: {
//               fontSize: "12px",
//               textTransform: "capitalize",
//               borderRadius: "6px",
//             },
//           },
//           grid: {
//             line: {
//               stroke: "#f3f4f6",
//             },
//           },
//         }}
//         role="application"
//       />
//     </div>
//   )
// }
