/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/M9y1jcxxJdY
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Candidats3() {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader className="flex flex-col items-center space-y-2.5">
        <div className="flex items-center space-x-4">
          <img
            alt="Candidate"
            className="rounded-full"
            height="80"
            src="/placeholder.svg"
            style={{
              aspectRatio: "80/80",
              objectFit: "cover",
            }}
            width="80"
          />
          <div className="text-center">
            <CardTitle className="text-lg font-bold">Aminata Touré</CardTitle>
            <CardDescription className="text-sm">Presidential Candidate</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="flex flex-col gap-1.5">
            <div className="text-sm font-medium text-gray-500 dark:text-gray-400">Total Votes</div>
            <div className="text-2xl font-bold">4,231,890</div>
          </div>
          <div className="flex flex-col gap-1.5">
            <div className="text-sm font-medium text-gray-500 dark:text-gray-400">Percentage of Votes</div>
            <div className="text-2xl font-bold">45.2%</div>
          </div>
        </div>
        <Card className="w-full">
          <CardHeader className="pb-0">
            <CardTitle className="text-sm font-medium">Votes by Region</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table className="w-full text-sm">
              <TableHeader>
                <TableRow>
                  <TableHead>Region</TableHead>
                  <TableHead className="text-right">Votes</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>Dakar</TableCell>
                  <TableCell className="text-right">1,231,890</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Thiès</TableCell>
                  <TableCell className="text-right">1,000,000</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Ziguinchor</TableCell>
                  <TableCell className="text-right">800,000</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Saint-Louis</TableCell>
                  <TableCell className="text-right">200,000</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Tambacounda</TableCell>
                  <TableCell className="text-right">300,000</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </CardContent>
    </Card>
  )
}
