/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BXskIstK22A
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Home5() {
  return (
    <div className="grid gap-4 w-full min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <a className="flex items-center gap-2" href="#">
          <Package2Icon className="w-6 h-6" />
          <span className="sr-only">Acme Inc</span>
        </a>
        <nav className="hidden gap-4 text-sm font-medium md:flex md:items-center md:gap-5 lg:gap-4">
          <a className="font-bold" href="#">
            Home
          </a>
          <a className="text-gray-500 dark:text-gray-400" href="#">
            Candidates
          </a>
          <a className="text-gray-500 dark:text-gray-400" href="#">
            Issues
          </a>
          <a className="text-gray-500 dark:text-gray-400" href="#">
            News
          </a>
          <animateTransform className="text-gray-500 dark:text-gray-400" href="#">
            About
          </animateTransform>
        </nav>
        <div className="ml-auto flex items-center gap-4 md:gap-2">
          <Button size="sm" variant="outline">
            Sign In
          </Button>
          <Button size="sm" variant="outline">
            Sign Up
          </Button>
        </div>
      </header>
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="grid gap-4 md:grid-cols-2">
          <div className="flex flex-col gap-2">
            <h1 className="text-3xl font-bold">Senegal Presidential Election</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Stay informed with live updates on the 2024 Senegal Presidential Election.
            </p>
          </div>
          <div className="flex flex-col items-end gap-2">
            <div className="flex items-center gap-2">
              <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
              <span className="text-sm">May 12, 2024</span>
            </div>
            <Button className="rounded-full" size="sm" variant="outline">
              <BookmarkIcon className="w-4 h-4 mr-2" />
              Save
            </Button>
          </div>
        </div>
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <CardTitle className="text-xl font-bold">Aminata Toure</CardTitle>
                <CardDescription className="text-sm">Independent Candidate</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Age: 52</span>
              </div>
              <div className="flex items-center gap-2">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Region: Dakar</span>
              </div>
              <div className="flex items-center gap-2">
                <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Experience: Former Prime Minister</span>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <CardTitle className="text-xl font-bold">Ousmane Sonko</CardTitle>
                <CardDescription className="text-sm">PASTEF-Les Patriotes</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Age: 47</span>
              </div>
              <div className="flex items-center gap-2">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Region: Ziguinchor</span>
              </div>
              <div className="flex items-center gap-2">
                <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Experience: Former MP</span>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <CardTitle className="text-xl font-bold">Macky Sall</CardTitle>
                <CardDescription className="text-sm">Coalition Benno Bokk Yakaar</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Age: 60</span>
              </div>
              <div className="flex items-center gap-2">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Region: Fatick</span>
              </div>
              <div className="flex items-center gap-2">
                <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Experience: President of Senegal</span>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <CardTitle className="text-xl font-bold">Khalifa Sall</CardTitle>
                <CardDescription className="text-sm">Coalition Taxawu Dakar</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Age: 65</span>
              </div>
              <div className="flex items-center gap-2">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Region: Dakar</span>
              </div>
              <div className="flex items-center gap-2">
                <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Experience: Former Mayor of Dakar</span>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <CardTitle className="text-xl font-bold">Idrissa Seck</CardTitle>
                <CardDescription className="text-sm">Coalition Idy 2019</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Age: 60</span>
              </div>
              <div className="flex items-center gap-2">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Region: Thiès</span>
              </div>
              <div className="flex items-center gap-2">
                <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Experience: Former Prime Minister</span>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <img
                alt="Candidate"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="flex flex-col">
                <CardTitle className="text-xl font-bold">Issa Sall</CardTitle>
                <CardDescription className="text-sm">Coalition Taxawu Dakar</CardDescription>
              </div>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <UserIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Age: 65</span>
              </div>
              <div className="flex items-center gap-2">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Region: Dakar</span>
              </div>
              <div className="flex items-center gap-2">
                <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span>Experience: Former Mayor of Dakar</span>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function Package2Icon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function CalendarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}


function BookmarkIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function MapPinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}
